#!/bin/sh

# Copyright (c) 2018 Silviu Chiricescu
# All rights reserved.
#
# Portions of this software were developed by BAE Systems, the University of
# Cambridge Computer Laboratory, and Memorial University under DARPA/AFRL
# contract FA8650-15-C-7558 ("CADETS"), as part of the DARPA Transparent
# Computing (TC) research program.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $FreeBSD$
#

# Sets up the pkg repository to point to our CADETS repo.
# To enable this functionality, add the
# following to /etc/rc.conf.local or /etc/rc.conf:
#
# cadets_pkg_bootstrap_enable="YES"
#

# PROVIDE: cadets_pkg_bootstrap
# REQUIRE: FILESYSTEMS NETWORKING growfs
# BEFORE: LOGIN local pkg_bootstrap
# KEYWORD: cadets_bootstrap

. /etc/rc.subr

name="cadets_pkg_bootstrap"
desc="Bootstrap the repository for pkg(8) pointing it to CADETS builds"
rcvar=cadets_pkg_bootstrap_enable
start_cmd="cadets_pkg_bootstrap_start"
stop_cmd=":"

: ${cadets_pkg_bootstrap_enable:="NO"}

cadets_pkg_bootstrap_start()
{

    mkdir -p /usr/local/etc/pkg/repos/
    # disable the FreeBSD pkg repo
    echo "FreeBSD: { enabled: no }" > /usr/local/etc/pkg/repos/FreeBSD.conf
    # enable the cadets-e5 repo
    cat > /usr/local/etc/pkg/repos/cadets-e5.conf <<EOF
# $cadets-e5$
#   
# MIRROR_TYPE of NONE,  any of the URL schemes supported by
#     libfetch(3) can be used, including: http://, https://, ftp://, or
#     file://.  In addition a ssh:// URL scheme is also supported.
# temp disable the pubkey signature type

cadets-e5: {
  url: "https://allendale.engr.mun.ca/cadets/e5/packages/FreeBSD:13:amd64/latest",
  mirror_type: "none",
#  signature_type: "pubkey",
#  pubkey: "/usr/share/keys/pkg/trusted/cadets-e5_pub.txt",
  enabled: yes
}
EOF

    # add the public keys to the cadets-e5 repo
    mkdir -p /usr/share/keys/pkg/trusted
    cat > /usr/share/keys/pkg/trusted/cadets-e5_pub.txt <<EOF
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAoLkHnTb9xE6yUV5YR//Y
oDvEAZyAlZmzPeZBlOd3kjcIsqvzFUF4rab2/UZX3m+4F24h8GBTHqnUWJFBdqi/
K3DHoqJxB3bIjL8XD3olICiF+Kq3caO94fb/LZXX61xzsirrBu4wWd0/p7e/+bWx
WDAvNFSihOu/5B4A+bfRrmXwDcO9mlHRS0tp5n+z12calELm5m+RUuEyjms4KaUi
QGIMpl+ViYEz8c6AHK64kNaaTJmGpSEFtm9JVTWh9ozsEjQz9zVo9aEluEgTsn+1
PdW1CmvmTIdNkCEWDwB1QC5vWqmiGj21VD02qpdwutC2KaSi+yLe8F4nZcXXzXQK
vqJq6PsCyn0ZB8qKWcmvWrQ94WpXNoh+OtTfNjUUnZeu2AVqdLJpwk4zVZq8vfGP
13z+df7aN9YNHSfuD3vtWMG84Rp5wIlL/5kovpRLiWf0UNlDcAQouayLWkvxuoRT
J4lIzbyM9D17soJMjDwJlgufiUlii/RFmgwG84qNIW4mk8N3DtpUC+FM1tA7NvM5
92yiknwY+i+OPV0DggN+g86i53WNbosF1K1wgUlkobEJN5HPIdAJJeMG3/28yED1
6RxtQnUY1YjfWNX5a4xBKbwMYHqs/0PRdCZ9rJP0xLBKJdAeGEUrOmhu4QqmovPQ
+3LIb8MFakMfCNxXD2Ye/80CAwEAAQ==
-----END PUBLIC KEY-----
EOF

    # update the pkg database
    pkg update
}

load_rc_config $name
run_rc_command "$1"
