#!/bin/sh

# Copyright (c) 2018 Silviu Chiricescu
# All rights reserved.
#
# Portions of this software were developed by BAE Systems, the University of
# Cambridge Computer Laboratory, and Memorial University under DARPA/AFRL
# contract FA8650-15-C-7558 ("CADETS"), as part of the DARPA Transparent
# Computing (TC) research program.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $FreeBSD$
#

# Sets up the pkg repository to point to our CADETS repo.
# To enable this functionality, add the
# following to /etc/rc.conf.local or /etc/rc.conf:
#
# firstboot_enable="YES"
# firstboot_bootstrap_packages="nginx xfce"  # etc.
# cadets_usr_bootstrap_list="bbn darpa" #etc.

# PROVIDE: firstboot
# REQUIRE: FILESYSTEMS NETWORKING growfs
# BEFORE: LOGIN local
# KEYWORD: firstboot

. /etc/rc.subr

name="firstboot"
desc="Bootstrap the repository for pkg(8) pointing it to CADETS builds"
rcvar=firstboot_enable
start_cmd="firstboot_start"
stop_cmd=":"

: ${firstboot_enable:="NO"}

firstboot_start()
{
    # first ensure that pkg points to the CADETS repo on allendale
    
    mkdir -p /usr/local/etc/pkg/repos/
    # disable the FreeBSD pkg repo
    echo "FreeBSD: { enabled: no }" > /usr/local/etc/pkg/repos/FreeBSD.conf
    # enable the cadets-e5 repo
    cat > /usr/local/etc/pkg/repos/cadets-e5.conf <<EOF
# $cadets-e5$
#   
# MIRROR_TYPE of NONE,  any of the URL schemes supported by
#     libfetch(3) can be used, including: http://, https://, ftp://, or
#     file://.  In addition a ssh:// URL scheme is also supported.
# temp disable the pubkey signature type

cadets-e5: {
  url: "https://allendale.engr.mun.ca/cadets/e5/packages/FreeBSD:13:amd64/latest",
  mirror_type: "none",
#  signature_type: "pubkey",
#  pubkey: "/usr/share/keys/pkg/trusted/cadets-e5_pub.txt",
  enabled: yes
}
EOF

    # add the public keys to the cadets-e5 repo
    mkdir -p /usr/share/keys/pkg/trusted
    cat > /usr/share/keys/pkg/trusted/cadets-e5_pub.txt <<EOF
R-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAoLkHnTb9xE6yUV5YR//Y
oDvEAZyAlZmzPeZBlOd3kjcIsqvzFUF4rab2/UZX3m+4F24h8GBTHqnUWJFBdqi/
K3DHoqJxB3bIjL8XD3olICiF+Kq3caO94fb/LZXX61xzsirrBu4wWd0/p7e/+bWx
WDAvNFSihOu/5B4A+bfRrmXwDcO9mlHRS0tp5n+z12calELm5m+RUuEyjms4KaUi
QGIMpl+ViYEz8c6AHK64kNaaTJmGpSEFtm9JVTWh9ozsEjQz9zVo9aEluEgTsn+1
PdW1CmvmTIdNkCEWDwB1QC5vWqmiGj21VD02qpdwutC2KaSi+yLe8F4nZcXXzXQK
vqJq6PsCyn0ZB8qKWcmvWrQ94WpXNoh+OtTfNjUUnZeu2AVqdLJpwk4zVZq8vfGP
13z+df7aN9YNHSfuD3vtWMG84Rp5wIlL/5kovpRLiWf0UNlDcAQouayLWkvxuoRT
J4lIzbyM9D17soJMjDwJlgufiUlii/RFmgwG84qNIW4mk8N3DtpUC+FM1tA7NvM5
92yiknwY+i+OPV0DggN+g86i53WNbosF1K1wgUlkobEJN5HPIdAJJeMG3/28yED1
6RxtQnUY1YjfWNX5a4xBKbwMYHqs/0PRdCZ9rJP0xLBKJdAeGEUrOmhu4QqmovPQ
+3LIb8MFakMfCNxXD2Ye/80CAwEAAQ==
-----END PUBLIC KEY-----
EOF

    # update the pkg database
    pkg update

    # next, install the requested users
    for usr in ${cadets_usr_bootstrap_list}; do
	pw useradd -n ${usr} -c ${usr} -s /bin/sh -m -w yes
    done
    
    # finally, install the required packages
    
    # The packages we install may install new rc scripts. Count the current
    # rc scripts in /usr/local/etc to detect this for later comparison.
    local_rc_scripts=`ls /usr/local/etc/rc.d | wc -l`
    
    # Bootstrap pkg(8)
    if ! pkg -N 2>/dev/null; then
	env ASSUME_ALWAYS_YES=YES pkg bootstrap |
	    cat
    fi
    
    # Install any requested packages
    for package in ${firstboot_bootstrap_packages}; do
	env ASSUME_ALWAYS_YES=YES pkg install ${package} </dev/null |
	    cat
    done
    
    # Count rc.d scripts again, and if there are more then request a
    # reboot to catch the new scripts
    local_rc_scripts_postinst=`ls /usr/local/etc/rc.d | wc -l`
    
    # If we have more scripts, request a reboot
    if [ $local_rc_scripts -ne $local_rc_scripts_postinst ]; then
	echo "Requesting reboot after installation of new rc.d scripts"
	touch ${firstboot_sentinel}-reboot
    fi

}

load_rc_config $name
run_rc_command "$1"
