#!/bin/sh

# Copyright (c) 2018 Silviu Chiricescu
# All rights reserved.
#
# Portions of this software were developed by BAE Systems, the University of
# Cambridge Computer Laboratory, and Memorial University under DARPA/AFRL
# contract FA8650-15-C-7558 ("CADETS"), as part of the DARPA Transparent
# Computing (TC) research program.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $FreeBSD$
#

# Sets up the pkg repository to point to our CADETS repo.
# To enable this functionality, add the
# following to /etc/rc.conf.local or /etc/rc.conf:
#
# firstboot_enable="YES"
# firstboot_bootstrap_packages="nginx xfce"  # etc.
# cadets_usr_bootstrap_list="bbn darpa" #etc.

# PROVIDE: firstboot
# REQUIRE: FILESYSTEMS NETWORKING growfs
# BEFORE: LOGIN local
# KEYWORD: firstboot

. /etc/rc.subr

name="firstboot"
desc="Bootstrap the repository for pkg(8) pointing it to CADETS builds"
rcvar=firstboot_enable
start_cmd="firstboot_start"
stop_cmd=":"

: ${firstboot_enable:="NO"}

firstboot_start()
{
    # first ensure that pkg points to the CADETS repo on allendale
    
    mkdir -p /usr/local/etc/pkg/repos/
    # disable the FreeBSD pkg repo
    echo "FreeBSD: { enabled: no }" > /usr/local/etc/pkg/repos/FreeBSD.conf
    # enable the cadets-e4 repo
    cat > /usr/local/etc/pkg/repos/cadets-e4.conf <<EOF
# $cadets-e4$
#   
# MIRROR_TYPE of NONE,  any of the URL schemes supported by
#     libfetch(3) can be used, including: http://, https://, ftp://, or
#     file://.  In addition a ssh:// URL scheme is also supported.
# temp disable the pubkey signature type

cadets-e4: {
  url: "https://allendale.engr.mun.ca/cadets/e4/packages/FreeBSD%3A12%3Aamd64/latest",
  mirror_type: "none",
#  signature_type: "pubkey",
#  pubkey: "/usr/share/keys/pkg/trusted/cadets-e4_pub.txt",
  enabled: yes
}
EOF

    # add the public keys to the cadets-e4 repo
    mkdir -p /usr/share/keys/pkg/trusted
    cat > /usr/share/keys/pkg/trusted/cadets-e4_pub.txt <<EOF
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA2Xm7NWk1bfBYmuoINHj+
7leABoiSSZwjKEpl03jsjgnrbNhSQHJJF/PhsBMvHP1nEDLcIYnP0HDrUp4DAjd9
RZY4p+gggxz9sTt9z+ABsCY96BgRVLis6hXuBcpWuKGVCBA7qLnZh6XcDBPpAoGy
fE4JOpCYyY3FFvDl8Au7lI+yU8idVPNCd2ZckWCJ7p05suUizCF9i/kYjFn5KlhK
qi7Nu9N8kl3VlTI/Z+jRXFqR3iD+wCWj9hM0kK92KvNfCo4/DPVEImXm7DSGfLIe
s6GNNkYWUyHK3fpMdD5g27zSUuWha456ZnIY1p/x9E7MNwlaVzm0tXwGogM7ZXqV
fsDGdRg+bNoI1/UlZf3npF6Oi2Rb58CSl0juNdGB1IJnOl20i18GrN3nOLHCUOhS
w0lxZQbQZunN6V6WHZKbcRuZvs7enOYqAD7kuZpJ6VpoEYetTSmjd+gwYLHPY1bB
Ocm+o3W+O3DVSmh8nINFWmbd/RndDxELv+jxBftUcfJXH7xd23ozAxqacKiAQz9f
y+YDP/InmEfAQbF2tYg9/koUyMgFc63j14JYf3Zzt9T+qHWzM7lYyuBZ4BP0FXLp
B4l92TeFexR4F7vvSWT3UfiudyKaEPWRXtbgcJY+owv7wxxuJWIpxYIRvSxkrXHW
RXEL+2P/8kgbTxYHBClE0pUCAwEAAQ==
-----END PUBLIC KEY-----
EOF

    # update the pkg database
    pkg update

    # next, install the requested users
    for usr in ${cadets_usr_bootstrap_list}; do
	pw useradd -n ${usr} -c ${usr} -s /bin/sh -m -w yes
    done
    
    # finally, install the required packages
    
    # The packages we install may install new rc scripts. Count the current
    # rc scripts in /usr/local/etc to detect this for later comparison.
    local_rc_scripts=`ls /usr/local/etc/rc.d | wc -l`
    
    # Bootstrap pkg(8)
    if ! pkg -N 2>/dev/null; then
	env ASSUME_ALWAYS_YES=YES pkg bootstrap |
	    cat
    fi
    
    # Install any requested packages
    for package in ${firstboot_bootstrap_packages}; do
	env ASSUME_ALWAYS_YES=YES pkg install ${package} </dev/null |
	    cat
    done
    
    # Count rc.d scripts again, and if there are more then request a
    # reboot to catch the new scripts
    local_rc_scripts_postinst=`ls /usr/local/etc/rc.d | wc -l`
    
    # If we have more scripts, request a reboot
    if [ $local_rc_scripts -ne $local_rc_scripts_postinst ]; then
	echo "Requesting reboot after installation of new rc.d scripts"
	touch ${firstboot_sentinel}-reboot
    fi

}

load_rc_config $name
run_rc_command "$1"
