#!/bin/sh
#
# Copyright (c) 2013, 2014, 2017 Colin Percival
# Copyright (c) 2018 Jonathan Anderson
# All rights reserved.
#
# Portions of this software were developed by BAE Systems, the University of
# Cambridge Computer Laboratory, and Memorial University under DARPA/AFRL
# contract FA8650-15-C-7558 ("CADETS"), as part of the DARPA Transparent
# Computing (TC) research program.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $FreeBSD$
#

#
# Install packages the first time the system comes up.
#
# When cross-building VMs, it may not be possible to run `pkg --chroot` from the
# build environment. As an alternative, this script allows packages to be
# automatically installed on first boot. To enable this functionality, add the
# following to /etc/rc.conf.local or /etc/rc.conf:
#
# pkg_bootstrap_enable="YES"
# pkg_bootstrap_packages="nginx xfce"  # etc.
#

# PROVIDE: pkg_bootstrap
# REQUIRE: FILESYSTEMS NETWORKING growfs
# BEFORE: LOGIN
# KEYWORD: bootstrap

. /etc/rc.subr

name="pkg_bootstrap"
desc="Bootstrap pkg(8) and an (optional) set of packages"
rcvar=pkg_bootstrap_enable
start_cmd="pkg_bootstrap_start"
stop_cmd=":"

: ${pkg_bootstrap_enable:="NO"}

pkg_bootstrap_start()
{

	# The packages we install may install new rc scripts. Count the current
	# rc scripts in /usr/local/etc to detect this for later comparison.
	local_rc_scripts=`ls /usr/local/etc/rc.d | wc -l`

	# Bootstrap pkg(8)
	if ! pkg -N 2>/dev/null; then
		env ASSUME_ALWAYS_YES=YES pkg bootstrap |
		    cat
	fi

	# Install any requested packages
	for package in ${pkg_bootstrap_packages}; do
		env ASSUME_ALWAYS_YES=YES pkg install ${package} </dev/null |
		    cat
	done

	# Count rc.d scripts again, and if there are more then request a
	# reboot to catch the new scripts
	local_rc_scripts_postinst=`ls /usr/local/etc/rc.d | wc -l`

	# If we have more scripts, request a reboot
	if [ $local_rc_scripts -ne $local_rc_scripts_postinst ]; then
		echo "Requesting reboot after installation of new rc.d scripts"
		touch ${firstboot_sentinel}-reboot
	fi
}

load_rc_config $name
run_rc_command "$1"
